os: osx
osx_image: xcode9.4

before_install:
# install xquartz
  - sh Manage\ Conky/Resources/InstallXQuartz.sh https://dl.bintray.com/xquartz/downloads/XQuartz-2.7.11.dmg

# install libraries
  - brew install cmake freetype gettext lua imlib2
  - brew link gettext --force

install:
  - xcodebuild Manage\ Conky.xcworkspace

