language: objective-c
os: osx
osx_image: xcode9.4
xcode_project: Manage\ Conky.xcworkspace
xcode_scheme: Manage\ Conky

before_install:
# install dependancies
  - brew install freetype gettext lua imlib2
  - brew link gettext --force

# setup xcode project
  - cd ConkyX/conky-for-macOS/forConkyX
  - cmake .. -G Xcode
  - cd ../../..
