language: objective-c
os: osx
osx_image: xcode9.4

before_install:
# install dependancies
  - brew install freetype gettext lua imlib2
  - brew link gettext --force

# setup cocoapods
  - pod update

# setup xcode project
  - cd ConkyX/conky-for-macOS/forConkyX
  - cmake .. -G Xcode
  - cd ../../..

install:
  - xcodebuild -workspace Manage\ Conky.xcworkspace -scheme Manage\ Conky
